### ISSUE TITLE
Required key not provided @ data['hub_id']. Got None

### ISSUE THREAD

**Issue by cjoha** [mtgeekman/Home_Assistant_NeoSmartBlinds#16]
Hi there,

I'm running Home Assistant 2021.6.3, as a supervised install (Home Assistant OS 5.13). I've installed this integration to control neosmartblinds over the static IP I have assigned to the neosmartblinds controller. My config is below:

  - platform: neosmartblinds
    name: All Kitchen Roller Blinds
    host: 192.168.8.43
    blind_code: 073.065-15
    close_time: 30
    hub_id: 23004e000251353532373238
    protocol: http
    port: 8838
    rail: 1
    percent_support: 0
    motor_code: bf

On reboots I can see the following error reported. I'm fairly sure the integration does not like the characters included in the hubID key, but I've checked and this is the hubID my app is reporting on my iPhone.

Are you seeing similar errors?

**Comment by mtgeekman** [comment]
Interesting,  the hub ID appears fine to me.  

Which version did you download from here?  1.5?

**Comment by cjoha** [comment]
It would have been the latest version, I just ran "git clone https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds.git"

**Comment by mtgeekman** [comment]
your config for this should be similar to mine as below: 

```
cover:
  - platform: neosmartblinds
    name: Bedroom South Blind
    host: 192.168.1.xx
    hub_id: L0nloxdZUCq30xxxxxxxxxxx
    protocol: http
    port: 8838
    blind_code: 044.171-01
    close_time: 26
```


I believe you can drop the last 3 lines:

rail: 1
percent_support: 0
motor_code: bf

as those are default values and the motor code only makes a difference for the 'no' motors currently.
