### ISSUE TITLE
Unable to Install from HACS

### ISSUE THREAD

**Issue by freemchr** [mtgeekman/Home_Assistant_NeoSmartBlinds#50]
When downloaded, this will be located in '/config/custom_components/neosmartblinds'
Remember that you need to restart Home Assistant before changes to integrations (custom_components) are applied.

Unknown error

When trying to download. Any ideas on how to fix?

**Comment by harobwh** [comment]
I also having the same issue. Please help

**Comment by mtgeekman** [comment]
I believe I had a mistake in the hacs.json file. I changed the line causing problems.  doing some testing now.

**Comment by mtgeekman** [comment]
@freemchr @harobwh 
Please give it another shot, make sure the version its trying to download is 2.3.3.  it should be working now.  Let me know if you are good to go please.

**Comment by freemchr** [comment]
Appears to be working now thanks @mtgeekman 

Quick one, how do i add multiple blinds to the configuration file? 

I also noted, that after I installed via HACS, and also edited the configuration file. I cannot add the entity cover? cant find it. Is there anything else i need to do?

**Comment by mtgeekman** [comment]
here is an example of what I have setup for 3 blinds: 

```
cover:
  - platform: neosmartblinds
    name: Bedroom South Blind
    host: 192.168.x.x
    hub_id: <hub_id_here>
    protocol: http
    port: 8838
    blind_code: 044.171-01
    close_time: 26
    rail: 1
    motor_code: "bf"
  - platform: neosmartblinds
    name: Bedroom East Blind
    host: 192.168.x.x
    hub_id: <hub_id_here>
    protocol: http
    port: 8838
    rail: 1
    blind_code: 044.171-02
    close_time: 26
  - platform: neosmartblinds
    name: French Doors
    host: 192.168.x.x
    hub_id: <hub_id_here>
    protocol: http
    port: 8838
    rail: 1
    blind_code: 237.120-01
    close_time: 26
    motor_code: "no"
    percent_support: 1
    start_position: 0
```

**Comment by freemchr** [comment]
Thanks. I have managed to setup, but for some reason not controlling the blinds, yet works from the neosmart app. Any ideas?

cover:
  - platform: neosmartblinds
    name: Patio Left
    host: 192.168.1.XX
    hub_id: XX
    protocol: http
    port: 8838
    blind_code: 041.025-00
    close_time: 26
    rail: 1
    percent_support: 0
    motor_code: wt
    start_position: 0
    parent_group: 041.025-15
  - platform: neosmartblinds
    name: Patio Right
    host: XX
    hub_id: XX
    protocol: http
    port: 8838
    blind_code: 041.025-01
    close_time: 26
    rail: 1
    percent_support: 0
    motor_code: wt
    start_position: 0
    parent_group: 041.025-15

**Comment by mtgeekman** [comment]
My only guess would be that home assistant isn't talking to the hub.  

Is there any information in the logs when you try to control the blinds?

**Comment by freemchr** [comment]
No errors at all in the logs.

**Comment by mtgeekman** [comment]
can you add this to your configuration.yaml? 

logger: 
  default: error 
  logs: 
    custom_components.neosmartblinds: debug
    
    
then give it another shot?

**Comment by ufondu88** [comment]
I get this error

```
Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:245
integration: neosmartblinds (documentation, issues)
First occurred: 1:10:56 PM (8 occurrences)
Last logged: 1:18:17 PM

Parameters: {'id': 'xxxxxxxxxxxxxx', 'command': 'xxx.yyy-01-dn', 'hash': '0492971'}
Parameters: {'id': 'xxxxxxxxxxxxxx', 'command': 'xxx.yyy-01-sp', 'hash': '0192461'}
Parameters: {'id': 'xxxxxxxxxxxxxx', 'command': 'xxx.yyy-01-dn', 'hash': '0892075'}
Parameters: {'id': 'xxxxxxxxxxxxxx', 'command': 'xxx.yyy-01-dn', 'hash': '0055616'}
Parameters: {'id': 'xxxxxxxxxxxxxx', 'command': 'xxx.yyy-01-dn', 'hash': '0698615'}
```


```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:148
First occurred: 1:09:24 PM (12 occurrences)
Last logged: 1:18:19 PM

Error doing job: Exception in callback _SelectorSocketTransport._call_connection_lost(None) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1181, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 901, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/usr/local/lib/python3.12/site-packages/aiohomekit/controller/ip/connection.py", line 89, in connection_lost
    self._cancel_pending_requests()
  File "/usr/local/lib/python3.12/site-packages/aiohomekit/controller/ip/connection.py", line 162, in _cancel_pending_requests
    result.set_exception(AccessoryDisconnectedError("Connection closed"))
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by mtgeekman** [comment]
can you share your config?  that make me think there is an issue.

**Comment by ufondu88** [comment]
```
cover: 
  - platform: neosmartblinds
    name: Office Blind 1
    host: 192.168.86.41
    hub_id: xxxxxxxxxxxxxx
    protocol: http
    port: 8838
    blind_code: xxx.yyy-01
    close_time: 30

  - platform: neosmartblinds
    name: Office Blind 2
    host: 192.168.86.41
    hub_id: xxxxxxxxxxxxxx
    protocol: http
    port: 8838
    blind_code: xxx.yyy-02
    close_time: 30

  - platform: neosmartblinds
    name: Dining Blind 1
    host: 192.168.86.41
    hub_id: xxxxxxxxxxxxxx
    protocol: http
    port: 8838
    blind_code: aaa.bbb-01
    close_time: 30

  - platform: neosmartblinds
    name: Dining Blind 2
    host: 192.168.86.41
    hub_id: xxxxxxxxxxxxxx
    protocol: http
    port: 8838
    blind_code: aaa.bbb-02
    close_time: 30
```
